[package]
name = "LgebraRust"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.32.5", features = ["rand"] }
rand = "0.8.5"
plotly = "0.8.4"
rayon = "1.10.0"
linregress = "0.5.3"